# Generated by Django 5.2.7 on 2025-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_desejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinil',
            name='para_troca',
            field=models.BooleanField(default=False),
        ),
    ]
