# Generated by Django 5.2.6 on 2025-10-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_update_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinil',
            name='conservacao_capa',
            field=models.CharField(choices=[('M', 'Mint (M)'), ('NM', 'Near Mint (NM or M-)'), ('VG+', 'Very Good Plus (VG+)'), ('VG', 'Very Good (VG)'), ('G+', 'Good Plus (G+)'), ('G', 'Good (G)')], default='VG', max_length=3),
        ),
        migrations.AddField(
            model_name='vinil',
            name='conservacao_disco',
            field=models.CharField(choices=[('M', 'Mint (M)'), ('NM', 'Near Mint (NM or M-)'), ('VG+', 'Very Good Plus (VG+)'), ('VG', 'Very Good (VG)'), ('G+', 'Good Plus (G+)'), ('G', 'Good (G)')], default='VG', max_length=3),
        ),
    ]
